language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-runtime

script: ./autogen.sh && ./configure && make

compiler:
  - clang
  - gcc

notifications:
  email:
    - jon@bringhurst.org
