/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum HVN_msg_type {
	BOOTSTRAP = 1,
	CONNECT = 2,
	CONSENSUS = 3,
	CONTROL = 4,
	DATA = 5,
	BOOTSTRAP_R = 6,
	CONNECT_R = 7,
	CONSENSUS_R = 8,
	CONTROL_R = 9,
	DATA_R = 10,
};
typedef enum HVN_msg_type HVN_msg_type;

struct HVN_replica_info {
	char uuid[16];
	int port;
	char *address;
};
typedef struct HVN_replica_info HVN_replica_info;

struct HVN_msg_bootstrap_t {
	HVN_msg_type type;
	char uuid[16];
	int port;
	char *address;
};
typedef struct HVN_msg_bootstrap_t HVN_msg_bootstrap_t;

struct HVN_msg_resp_bootstrap_t {
	HVN_msg_type type;
	bool_t success;
	struct {
		u_int known_replicas_len;
		HVN_replica_info *known_replicas_val;
	} known_replicas;
};
typedef struct HVN_msg_resp_bootstrap_t HVN_msg_resp_bootstrap_t;

struct HVN_msg_connect_t {
	char magic[4];
	char api_version[4];
	HVN_msg_type type;
};
typedef struct HVN_msg_connect_t HVN_msg_connect_t;

struct HVN_msg_resp_connect_t {
	char api_version[4];
	HVN_msg_type type;
	bool_t success;
};
typedef struct HVN_msg_resp_connect_t HVN_msg_resp_connect_t;

struct HVN_msg_consensus_t {
	HVN_msg_type_e type;
	bool_t is_vote;
	char uuid_id[16];
	u_long term;
	u_long log_index;
	u_long log_term;
	u_long commit_index;
	UT_array *log_entries;
};
typedef struct HVN_msg_consensus_t HVN_msg_consensus_t;

struct HVN_msg_resp_consensus_t {
	u_long term;
	bool_t success;
};
typedef struct HVN_msg_resp_consensus_t HVN_msg_resp_consensus_t;

enum HVN_msg_control_action_type {
	ATTACH_APPEND = 1,
	ATTACH_DATA = 2,
	ATTACH_VOTE = 3,
	IDLE_FOLLOWER = 4,
	DESTROY = 5,
	EXIT = 6,
};
typedef enum HVN_msg_control_action_type HVN_msg_control_action_type;

struct HVN_msg_control_t {
	HVN_msg_control_action_type action;
	char uuid[16];
};
typedef struct HVN_msg_control_t HVN_msg_control_t;

struct HVN_msg_resp_control_t {
	bool_t success;
};
typedef struct HVN_msg_resp_control_t HVN_msg_resp_control_t;

enum HVN_msg_data_transaction {
	SINGLE = 1,
	BEGIN = 2,
	COMMIT = 3,
	ABORT = 4,
};
typedef enum HVN_msg_data_transaction HVN_msg_data_transaction;

enum HVN_msg_data_verb {
	PUT = 1,
	GET = 2,
	DELETE = 3,
	WATCH = 4,
	UNWATCH = 5,
};
typedef enum HVN_msg_data_verb HVN_msg_data_verb;

enum HVN_msg_data_mode {
	READ_WRITE = 1,
	READ_ONLY = 2,
	READ_BOUNDED = 3,
	READ_TIMESTAMP = 4,
};
typedef enum HVN_msg_data_mode HVN_msg_data_mode;

struct HVN_msg_data_op_t {
	HVN_msg_data_verb verb;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct HVN_msg_data_op_t HVN_msg_data_op_t;

struct HVN_msg_data_t {
	HVN_msg_data_mode mode;
	HVN_msg_data_transaction transaction;
	struct {
		u_int ops_len;
		HVN_msg_data_op_t *ops_val;
	} ops;
};
typedef struct HVN_msg_data_t HVN_msg_data_t;

struct HVN_msg_resp_data_t {
	bool_t success;
};
typedef struct HVN_msg_resp_data_t HVN_msg_resp_data_t;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_HVN_msg_type (XDR *, HVN_msg_type*);
extern  bool_t xdr_HVN_replica_info (XDR *, HVN_replica_info*);
extern  bool_t xdr_HVN_msg_bootstrap_t (XDR *, HVN_msg_bootstrap_t*);
extern  bool_t xdr_HVN_msg_resp_bootstrap_t (XDR *, HVN_msg_resp_bootstrap_t*);
extern  bool_t xdr_HVN_msg_connect_t (XDR *, HVN_msg_connect_t*);
extern  bool_t xdr_HVN_msg_resp_connect_t (XDR *, HVN_msg_resp_connect_t*);
extern  bool_t xdr_HVN_msg_consensus_t (XDR *, HVN_msg_consensus_t*);
extern  bool_t xdr_HVN_msg_resp_consensus_t (XDR *, HVN_msg_resp_consensus_t*);
extern  bool_t xdr_HVN_msg_control_action_type (XDR *, HVN_msg_control_action_type*);
extern  bool_t xdr_HVN_msg_control_t (XDR *, HVN_msg_control_t*);
extern  bool_t xdr_HVN_msg_resp_control_t (XDR *, HVN_msg_resp_control_t*);
extern  bool_t xdr_HVN_msg_data_transaction (XDR *, HVN_msg_data_transaction*);
extern  bool_t xdr_HVN_msg_data_verb (XDR *, HVN_msg_data_verb*);
extern  bool_t xdr_HVN_msg_data_mode (XDR *, HVN_msg_data_mode*);
extern  bool_t xdr_HVN_msg_data_op_t (XDR *, HVN_msg_data_op_t*);
extern  bool_t xdr_HVN_msg_data_t (XDR *, HVN_msg_data_t*);
extern  bool_t xdr_HVN_msg_resp_data_t (XDR *, HVN_msg_resp_data_t*);

#else /* K&R C */
extern bool_t xdr_HVN_msg_type ();
extern bool_t xdr_HVN_replica_info ();
extern bool_t xdr_HVN_msg_bootstrap_t ();
extern bool_t xdr_HVN_msg_resp_bootstrap_t ();
extern bool_t xdr_HVN_msg_connect_t ();
extern bool_t xdr_HVN_msg_resp_connect_t ();
extern bool_t xdr_HVN_msg_consensus_t ();
extern bool_t xdr_HVN_msg_resp_consensus_t ();
extern bool_t xdr_HVN_msg_control_action_type ();
extern bool_t xdr_HVN_msg_control_t ();
extern bool_t xdr_HVN_msg_resp_control_t ();
extern bool_t xdr_HVN_msg_data_transaction ();
extern bool_t xdr_HVN_msg_data_verb ();
extern bool_t xdr_HVN_msg_data_mode ();
extern bool_t xdr_HVN_msg_data_op_t ();
extern bool_t xdr_HVN_msg_data_t ();
extern bool_t xdr_HVN_msg_resp_data_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
