#ifndef __HAVEN__HAVEND_STATE_CONSENSUS_EVENTS_H
#define __HAVEN__HAVEND_STATE_CONSENSUS_EVENTS_H

typedef enum HAVEN_state_events_consensus {
    HANDLE_LOG_APPEND = 0,
    HEARTBEAT_TIMEOUT = 1,
    ELECTION_TIMEOUT = 2,
    ELECTION_SUCCESS = 3,
    DISCOVERED_HIGHER_TERM = 4,
    SETUP_LOCATION_SERVICE = 5,
    JOIN_EXISTING_QUORUM = 6
    CREATE_REGULAR = 7,
    CREATE_LOCATION = 8,
    JOIN = 9,
    CREATE_NEW_QUORUM = 10
} HAVEN_state_events_consensus;

#endif /* __HAVEN_HAVEND_CONSENSUS_EVENTS_H */
