/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proto.h"

bool_t
xdr_TDB_proto_msg_type (XDR *xdrs, TDB_proto_msg_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_replica_info (XDR *xdrs, TDB_replica_info *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->address, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_bootstrap (XDR *xdrs, TDB_msg_bootstrap *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->address, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_bootstrap (XDR *xdrs, TDB_msg_resp_bootstrap *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->known_replicas.known_replicas_val, (u_int *) &objp->known_replicas.known_replicas_len, ~0,
		sizeof (TDB_replica_info), (xdrproc_t) xdr_TDB_replica_info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_connect (XDR *xdrs, TDB_msg_connect *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->magic, 4))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->api_version, 4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_connect (XDR *xdrs, TDB_msg_resp_connect *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->api_version, 4))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_consensus_log_entry (XDR *xdrs, TDB_msg_consensus_log_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_consensus (XDR *xdrs, TDB_msg_consensus *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->is_vote))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_index))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->commit_index))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->term);
		IXDR_PUT_U_LONG(buf, objp->log_index);
		IXDR_PUT_U_LONG(buf, objp->log_term);
		IXDR_PUT_U_LONG(buf, objp->commit_index);
		}
		 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
			sizeof (TDB_msg_consensus_log_entry), (xdrproc_t) xdr_TDB_msg_consensus_log_entry))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->is_vote))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_index))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->commit_index))
				 return FALSE;

		} else {
		objp->term = IXDR_GET_U_LONG(buf);
		objp->log_index = IXDR_GET_U_LONG(buf);
		objp->log_term = IXDR_GET_U_LONG(buf);
		objp->commit_index = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
			sizeof (TDB_msg_consensus_log_entry), (xdrproc_t) xdr_TDB_msg_consensus_log_entry))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_vote))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->term))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->log_index))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->log_term))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->commit_index))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
		sizeof (TDB_msg_consensus_log_entry), (xdrproc_t) xdr_TDB_msg_consensus_log_entry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_consensus (XDR *xdrs, TDB_msg_resp_consensus *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->term))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_control_action_type (XDR *xdrs, TDB_msg_control_action_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_control (XDR *xdrs, TDB_msg_control *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_TDB_msg_control_action_type (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_control (XDR *xdrs, TDB_msg_resp_control *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_transaction (XDR *xdrs, TDB_msg_data_transaction *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_verb (XDR *xdrs, TDB_msg_data_verb *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_mode (XDR *xdrs, TDB_msg_data_mode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_op (XDR *xdrs, TDB_msg_data_op *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_msg_data_verb (xdrs, &objp->verb))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data (XDR *xdrs, TDB_msg_data *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_TDB_msg_data_mode (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_TDB_msg_data_transaction (xdrs, &objp->transaction))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ops.ops_val, (u_int *) &objp->ops.ops_len, ~0,
		sizeof (TDB_msg_data_op), (xdrproc_t) xdr_TDB_msg_data_op))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_data (XDR *xdrs, TDB_msg_resp_data *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}
