/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proto.h"

bool_t
xdr_TDB_proto_msg_type_enum (XDR *xdrs, TDB_proto_msg_type_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_replica_info_t (XDR *xdrs, TDB_replica_info_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->address, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_bootstrap_t (XDR *xdrs, TDB_msg_bootstrap_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->address, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_bootstrap_t (XDR *xdrs, TDB_msg_resp_bootstrap_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->known_replicas.known_replicas_val, (u_int *) &objp->known_replicas.known_replicas_len, ~0,
		sizeof (TDB_replica_info_t), (xdrproc_t) xdr_TDB_replica_info_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_connect_t (XDR *xdrs, TDB_msg_connect_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->magic, 4))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->api_version, 4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_connect_t (XDR *xdrs, TDB_msg_resp_connect_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->api_version, 4))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_consensus_log_entry_t (XDR *xdrs, TDB_msg_consensus_log_entry_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_consensus_t (XDR *xdrs, TDB_msg_consensus_t *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->is_vote))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_index))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->commit_index))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->term);
		IXDR_PUT_U_LONG(buf, objp->log_index);
		IXDR_PUT_U_LONG(buf, objp->log_term);
		IXDR_PUT_U_LONG(buf, objp->commit_index);
		}
		 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
			sizeof (TDB_msg_consensus_log_entry_t), (xdrproc_t) xdr_TDB_msg_consensus_log_entry_t))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->is_vote))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_index))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->log_term))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->commit_index))
				 return FALSE;

		} else {
		objp->term = IXDR_GET_U_LONG(buf);
		objp->log_index = IXDR_GET_U_LONG(buf);
		objp->log_term = IXDR_GET_U_LONG(buf);
		objp->commit_index = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
			sizeof (TDB_msg_consensus_log_entry_t), (xdrproc_t) xdr_TDB_msg_consensus_log_entry_t))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_vote))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid_id, 16))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->term))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->log_index))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->log_term))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->commit_index))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->log_entries.log_entries_val, (u_int *) &objp->log_entries.log_entries_len, ~0,
		sizeof (TDB_msg_consensus_log_entry_t), (xdrproc_t) xdr_TDB_msg_consensus_log_entry_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_consensus_t (XDR *xdrs, TDB_msg_resp_consensus_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->term))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_control_action_type_enum (XDR *xdrs, TDB_msg_control_action_type_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_control (XDR *xdrs, TDB_msg_control *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_TDB_msg_control_action_type_enum (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->uuid, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_control_t (XDR *xdrs, TDB_msg_resp_control_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_transaction_enum (XDR *xdrs, TDB_msg_data_transaction_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_verb_enum (XDR *xdrs, TDB_msg_data_verb_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_mode_enum (XDR *xdrs, TDB_msg_data_mode_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_op_t (XDR *xdrs, TDB_msg_data_op_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_msg_data_verb_enum (xdrs, &objp->verb))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_data_t (XDR *xdrs, TDB_msg_data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_TDB_msg_data_mode_enum (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_TDB_msg_data_transaction_enum (xdrs, &objp->transaction))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ops.ops_val, (u_int *) &objp->ops.ops_len, ~0,
		sizeof (TDB_msg_data_op_t), (xdrproc_t) xdr_TDB_msg_data_op_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDB_msg_resp_data_t (XDR *xdrs, TDB_msg_resp_data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TDB_proto_msg_type_enum (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}
