/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "admin.pb-c.h"
void   haven__admin__modify_peers__peer__init
(Haven__Admin__ModifyPeers__Peer*         message)
{
    static Haven__Admin__ModifyPeers__Peer init_value = HVN__ADMIN__MODIFY_PEERS__PEER__INIT;
    *message = init_value;
}
void   haven__admin__modify_peers__init
(Haven__Admin__ModifyPeers*         message)
{
    static Haven__Admin__ModifyPeers init_value = HVN__ADMIN__MODIFY_PEERS__INIT;
    *message = init_value;
}
size_t haven__admin__modify_peers__get_packed_size
(const Haven__Admin__ModifyPeers* message)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__modify_peers__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}
size_t haven__admin__modify_peers__pack
(const Haven__Admin__ModifyPeers* message,
 uint8_t*       out)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__modify_peers__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}
size_t haven__admin__modify_peers__pack_to_buffer
(const Haven__Admin__ModifyPeers* message,
 ProtobufCBuffer* buffer)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__modify_peers__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}
Haven__Admin__ModifyPeers*
haven__admin__modify_peers__unpack
(ProtobufCAllocator*  allocator,
 size_t               len,
 const uint8_t*       data)
{
    return (Haven__Admin__ModifyPeers*)
           protobuf_c_message_unpack(&haven__admin__modify_peers__descriptor,
                                     allocator, len, data);
}
void   haven__admin__modify_peers__free_unpacked
(Haven__Admin__ModifyPeers* message,
 ProtobufCAllocator* allocator)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__modify_peers__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}
void   haven__admin__result__init
(Haven__Admin__Result*         message)
{
    static Haven__Admin__Result init_value = HVN__ADMIN__RESULT__INIT;
    *message = init_value;
}
size_t haven__admin__result__get_packed_size
(const Haven__Admin__Result* message)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__result__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}
size_t haven__admin__result__pack
(const Haven__Admin__Result* message,
 uint8_t*       out)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__result__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}
size_t haven__admin__result__pack_to_buffer
(const Haven__Admin__Result* message,
 ProtobufCBuffer* buffer)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__result__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}
Haven__Admin__Result*
haven__admin__result__unpack
(ProtobufCAllocator*  allocator,
 size_t               len,
 const uint8_t*       data)
{
    return (Haven__Admin__Result*)
           protobuf_c_message_unpack(&haven__admin__result__descriptor,
                                     allocator, len, data);
}
void   haven__admin__result__free_unpacked
(Haven__Admin__Result* message,
 ProtobufCAllocator* allocator)
{
    PROTOBUF_C_ASSERT(message->base.descriptor == &haven__admin__result__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor haven__admin__modify_peers__peer__field_descriptors[2] = {
    {
        "hostname",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(Haven__Admin__ModifyPeers__Peer, hostname),
        NULL,
        NULL,
        0,            /* packed */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "port",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_INT32,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(Haven__Admin__ModifyPeers__Peer, port),
        NULL,
        NULL,
        0,            /* packed */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};
static const unsigned haven__admin__modify_peers__peer__field_indices_by_name[] = {
    0,   /* field[0] = hostname */
    1,   /* field[1] = port */
};
static const ProtobufCIntRange haven__admin__modify_peers__peer__number_ranges[1 + 1] = {
    { 3, 0 },
    { 0, 2 }
};
const ProtobufCMessageDescriptor haven__admin__modify_peers__peer__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "haven.admin.modify_peers.peer",
    "Peer",
    "Haven__Admin__ModifyPeers__Peer",
    "haven.admin",
    sizeof(Haven__Admin__ModifyPeers__Peer),
    2,
    haven__admin__modify_peers__peer__field_descriptors,
    haven__admin__modify_peers__peer__field_indices_by_name,
    1,  haven__admin__modify_peers__peer__number_ranges,
    (ProtobufCMessageInit) haven__admin__modify_peers__peer__init,
    NULL, NULL, NULL  /* reserved[123] */
};
const ProtobufCEnumValue haven__admin__modify_peers__modify_type__enum_values_by_number[2] = {
    { "ADD", "HVN__ADMIN__MODIFY_PEERS__MODIFY_TYPE__ADD", 1 },
    { "REMOVE", "HVN__ADMIN__MODIFY_PEERS__MODIFY_TYPE__REMOVE", 2 },
};
static const ProtobufCIntRange haven__admin__modify_peers__modify_type__value_ranges[] = {
    {1, 0}, {0, 2}
};
const ProtobufCEnumValueIndex haven__admin__modify_peers__modify_type__enum_values_by_name[2] = {
    { "ADD", 0 },
    { "REMOVE", 1 },
};
const ProtobufCEnumDescriptor haven__admin__modify_peers__modify_type__descriptor = {
    PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
    "haven.admin.modify_peers.modify_type",
    "modify_type",
    "Haven__Admin__ModifyPeers__ModifyType",
    "haven.admin",
    2,
    haven__admin__modify_peers__modify_type__enum_values_by_number,
    2,
    haven__admin__modify_peers__modify_type__enum_values_by_name,
    1,
    haven__admin__modify_peers__modify_type__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};
static const ProtobufCFieldDescriptor haven__admin__modify_peers__field_descriptors[2] = {
    {
        "type",
        5,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_ENUM,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(Haven__Admin__ModifyPeers, type),
        &haven__admin__modify_peers__modify_type__descriptor,
        NULL,
        0,            /* packed */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "peers",
        6,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(Haven__Admin__ModifyPeers, n_peers),
        PROTOBUF_C_OFFSETOF(Haven__Admin__ModifyPeers, peers),
        &haven__admin__modify_peers__peer__descriptor,
        NULL,
        0,            /* packed */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};
static const unsigned haven__admin__modify_peers__field_indices_by_name[] = {
    1,   /* field[1] = peers */
    0,   /* field[0] = type */
};
static const ProtobufCIntRange haven__admin__modify_peers__number_ranges[1 + 1] = {
    { 5, 0 },
    { 0, 2 }
};
const ProtobufCMessageDescriptor haven__admin__modify_peers__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "haven.admin.modify_peers",
    "ModifyPeers",
    "Haven__Admin__ModifyPeers",
    "haven.admin",
    sizeof(Haven__Admin__ModifyPeers),
    2,
    haven__admin__modify_peers__field_descriptors,
    haven__admin__modify_peers__field_indices_by_name,
    1,  haven__admin__modify_peers__number_ranges,
    (ProtobufCMessageInit) haven__admin__modify_peers__init,
    NULL, NULL, NULL  /* reserved[123] */
};
static const ProtobufCFieldDescriptor haven__admin__result__field_descriptors[1] = {
    {
        "success",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_BOOL,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(Haven__Admin__Result, success),
        NULL,
        NULL,
        0,            /* packed */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};
static const unsigned haven__admin__result__field_indices_by_name[] = {
    0,   /* field[0] = success */
};
static const ProtobufCIntRange haven__admin__result__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor haven__admin__result__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "haven.admin.result",
    "Result",
    "Haven__Admin__Result",
    "haven.admin",
    sizeof(Haven__Admin__Result),
    1,
    haven__admin__result__field_descriptors,
    haven__admin__result__field_indices_by_name,
    1,  haven__admin__result__number_ranges,
    (ProtobufCMessageInit) haven__admin__result__init,
    NULL, NULL, NULL  /* reserved[123] */
};
static const ProtobufCMethodDescriptor haven__admin__admin__method_descriptors[1] = {
    { "peers", &haven__admin__modify_peers__descriptor, &haven__admin__result__descriptor },
};
const unsigned haven__admin__admin__method_indices_by_name[] = {
    0         /* peers */
};
const ProtobufCServiceDescriptor haven__admin__admin__descriptor = {
    PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
    "haven.admin.admin",
    "peers",
    "Haven__Admin__Admin",
    "haven.admin",
    1,
    haven__admin__admin__method_descriptors,
    haven__admin__admin__method_indices_by_name
};
void haven__admin__admin__peers(ProtobufCService* service,
                                const Haven__Admin__ModifyPeers* input,
                                Haven__Admin__Result_Closure closure,
                                void* closure_data)
{
    PROTOBUF_C_ASSERT(service->descriptor == &haven__admin__admin__descriptor);
    service->invoke(service, 0, (const ProtobufCMessage*) input, (ProtobufCClosure) closure, closure_data);
}
void haven__admin__admin__init(Haven__Admin__Admin_Service* service,
                               Haven__Admin__Admin_ServiceDestroy destroy)
{
    protobuf_c_service_generated_init(&service->base,
                                      &haven__admin__admin__descriptor,
                                      (ProtobufCServiceDestroy) destroy);
}
